# Wrangler configuration for Cloudflare Pages
name = "ejecs-docs"
compatibility_date = "2025-04-09"

[site]
bucket = ".output/public"

[build]
command = """
npm install --prefer-offline --no-audit --progress=false && \
npm run build && \
test -d .output/public || (echo "Build failed - output directory missing" && exit 1)
"""
output_dir = ".output/public"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--no-optional"

[env.production]
vars = { NITRO_PRESET = "cloudflare-pages" }

# Cache configuration
[cache]
# Static assets (images, fonts, etc)
[[cache.patterns]]
pattern = "/images/*"
ttl = 2592000 # 30 days

[[cache.patterns]]
pattern = "/fonts/*"
ttl = 2592000 # 30 days

[[cache.patterns]]
pattern = "/*.css"
ttl = 86400 # 1 day

[[cache.patterns]]
pattern = "/*.js"
ttl = 86400 # 1 day

[[cache.patterns]]
pattern = "/api/*"
ttl = 0 # No cache for API routes

[[cache.patterns]]
pattern = "/*"
ttl = 3600 # 1 hour for everything else

# Deployment safeguards
[deployment]
max_workers = 1
max_duration = 60
memory_limit = "1GB" 